trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Job1
    steps:
      - script: echo Job1 Hello, world, changed!
        displayName: "Run a one-line script"

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          echo more information
        displayName: "Run a multi-line script"

  - job: Job2
    steps:
      - script: echo Hello, world, changed to job2!
        displayName: "Run a one-line script job 2"
