trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Job1
    steps:
      - script: echo Job1 Hello, world, changed!
        displayName: "Run a one-line script"

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          echo more information
        displayName: "Run a multi-line script"

  - job: Job2
    dependsOn: Job1
    steps:
      - script: echo Hello, world, changed to job2!
        displayName: "Run a one-line scriptw job 2"
  - job: Job3
    dependsOn: Job2
    steps:
      - script: echo Hello, world, changed to job3!
        displayName: "Run a one-line script job 3"
  - job: Job4
    dependsOn:
    - Job2
    - Job3
    steps:
      - script: echo Hello, world, changed to job4!
        displayName: "Run a one-line script job 4"